### ISSUE TITLE
validateLoginCredentials logs misleading output on missing API key

### ISSUE THREAD

**Issue by FodT** [MediaMath/t1-java#26]
``` java 
if (apiKey == null || apiKey.isEmpty()) {
      logger.error("Environment does not exist");
      throw new ClientException("Please Provide Valid API Key");
 }
```

output shows  'Environment does not exist' - this is not a useful message. The exception message is much more useful.

**Comment by nitesh-chauhan** [comment]
created a pull request, validateLoginCredentials logs misleading output -- fixed
