### ISSUE TITLE
Missing Campaign property : impression_cap_automatic

### ISSUE THREAD

**Issue by nicolasdalsass** [MediaMath/t1-java#36]
The Campaign model object miss the field `impression_cap_automatic`, which is a bit inconvenient since it's a required one ([according to the developer doc](https://mediamath.api-docs.io/v2/campaigns/campaign)).

Would you be open to a PR to fix that ? If yes, do you need anything specific like a contributor agreement ? 

Thanks,
Nicolas

**Comment by FodT** [comment]
Hey nicolas! 

Woops, that's a bit of a miss there. Thanks for letting us know. Of course we're open to PRs!

**Comment by FodT** [comment]
Resolved by #37
