### ISSUE TITLE
Add code coverage using Sonar

### ISSUE THREAD

**Issue by karthik-mediamath** [MediaMath/t1-java#41]
Improve code coverage by fixing and writing new unit test cases.

**Comment by karthik-mediamath** [comment]
@jitendra-xoriant : Where are we on this issue?

**Comment by jitendra-xoriant** [comment]
I have covered most of the code, now need to write tests for Error Handling methods.
@karthik-mediamath  can you remove below folder as it mostly contain Internal Datastructures used in reporting API. We can not cover most of them.
"src/main/java/com/mediamath/terminalone/models/reporting/meta"

**Comment by karthik-mediamath** [comment]
Code coverage is now > 85% and hence closing this issue.
