### ISSUE TITLE
Missing 'name' fields from various entities

### ISSUE THREAD

**Issue by FodT** [MediaMath/t1-java#47]
The `name` field is missing from the following entity models:
`SupplySource` 
`Advertiser`
`Creative`
`CreativeApproval`
`PlacementSlot`
`StrategyAudienceSegment`
`StrategySupplySource` 
`StrategyTargetingSegment`
Many of these are also missing from the t1-python SDK, which is less of an issue since the library will create string properties for all fields returned regardless.

**Comment by karthik-mediamath** [comment]
`Advertiser` and `CreativeApproval` have got this param added already. Have added for the remaining missing entities. Code changes in branch `Issue47/MissingEntityName`. @nitesh-chauhan @jitendra-xoriant . Please review, add if anything missing and create a PR.

**Comment by karthik-mediamath** [comment]
`name` param is now added to the missing entities.
