### ISSUE TITLE
Provide more meaningful error responses 

### ISSUE THREAD

**Issue by karthik-mediamath** [MediaMath/t1-java#55]
For optional parameters that are conditionally required, rather than just proxying the API's - "Param X is required" we need to validate the response and send a more meaningful message to the client like "Param X is now required as we have Param Y set".

**Comment by jitendra-xoriant** [comment]
As per previous discussions with Prasanna and Fod, We do not validate request and response of T1-Java. All error messages we send to client, are directly coming from T1 mediamath API.

**Comment by FodT** [comment]
Agreed – the push-back here should be on the API to provide a more meaningful message. Attempting to second-guess dependencies on parameters in the SDK will replicate business logic and introduce another maintenance overhead.

**Comment by karthik-mediamath** [comment]
@FodT True, by right it should be the API which should take this responsibility. But given our API's short-comes should our SDK's take this so that we have happy clients is my thought.
