### ISSUE TITLE
AMOUNT field types inconsistent in AudienceSegment

### ISSUE THREAD

**Issue by vforvasanth** [MediaMath/t1-java#65]
The AudienceSegment.class is have the retail_cpm and wholesale_cpm values declared as float, but they are actually returned as objects, which cannot be cast. Try this:
https://api.mediamath.com/api/v2.0/audience_segments?sort_by=id&parent=27962&page_limit=100&full=*
Response:
        <entity name="Financial - FMCG Direct" id="133752" type="audience_segment" version="0">
            <prop name="audience_vendor_id" value="13" />
            <prop name="parent_audience_segment_id" value="27962" />
            <prop name="name" value="Financial - FMCG Direct" />
            <prop name="code" value="360861" />
            <prop name="wholesale_cpm" currency_code="USD" value="1.1481">
                <amount currency_code="USD" value="1.1481" />
            </prop>
            <prop name="retail_cpm" currency_code="USD" value="1.2500">
                <amount currency_code="USD" value="1.2500" />
            </prop>
            <prop name="buyable" value="1" />
            <prop name="created_on" value="2014-10-10T20:16:30" />
            <prop name="updated_on" value="2017-03-23T18:58:02" />
            <prop name="type" value="normal" />
            <prop name="full_path" value="Experian - Financial - FMCG Direct" />
            <prop name="child_count" value="11" />
        </entity>

**Comment by jitendra-xoriant** [comment]
Issue is fixed
