### ISSUE TITLE
Support Auth0 style Oauth2 flow. 

### ISSUE THREAD

**Issue by fsargent** [MediaMath/t1-java#70]
As an external developer, I'd like to authenticate against the MediaMath APIs using the SDK with the latest authorization standard, so I have a lot of time to migrate to a new system before Cookie Auth gets turned off.

- Support Oauth2-Resource Owner Flow

Client Credentials and Authorization Grant flow aren't technically necessary for this as it's unlikely that our services will use the SDKs (Client Credentials) or the SDKs will be used for web services (Authorization Code grant).

https://connect2id.com/products/nimbus-jose-jwt might be a good place to start.

Production: https://sso.mediamath.auth0.com/
Development: https://sso.mediamath-dev.auth0.com/

https://auth0.com/docs/api-auth/grant/password
https://auth0.com/docs/api-auth/tutorials/password-grant

**Comment by karthik-mediamath** [comment]
Added support for Auth0 style Oauth2 flow, so closing this issue.
