### ISSUE TITLE
Batch Update of Campaigns

### ISSUE THREAD

**Issue by fsargent** [MediaMath/t1-java#75]
As a user of the MediaMath SDKs, I'd like to be able to efficiently queue updates to campaigns, so that I can update thousands of campaigns quickly.

- Fetch all strategies to be uploaded in one call, gathering version info
- setup a queue to efficiently track the update status of each campaign.

-- Original Ticket --
[redacted] is using MediaMath java SDK to upload changes to [redacted] campaigns/strategies.

Currently, it takes 15 mins to update bids for a campaign that has 1000 strategies.

Each update requires the correct "version" marker for the strategy, which can slow down the API calls to fetch.

**Comment by karthik-mediamath** [comment]
Fixed in v1.1.0 for Ebay Usecase.
