### ISSUE TITLE
TerminalOne.class to support backup Image upload for creatives

### ISSUE THREAD

**Issue by vforvasanth** [MediaMath/t1-java#77]
Right now we have 
saveTOneASCreativeAssetsUpload(String filePath, String fileName, String name)
which helps upload a single creative file 

but in case of creatives files of type HTML5, we would need to upload a zip file followed by a backup file in the same call and would be great if TerminalOne can support this.

**Comment by vforvasanth** [comment]
@karthik-mediamath any updates on this issue? This would help us sync HTML5 creatives to Mediamath.

**Comment by karthik-mediamath** [comment]
@vforvasanth The code for html5 creative upload has been merged. New version will be released on Monday. You guys have made your own code for video creatives upload right? can you submit a PR for that to get merged into our repo?

**Comment by karthik-mediamath** [comment]
Fixed in v1.1.1. Thanks
